lsi: false
safe: true
# source: jekyll
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
domain: tushark1729-k.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://tushar1729-k.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/jekyll/"      # place folder name if the site is served in a subfolder